apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached-sample
    app.kubernetes.io/part-of: kube-operator-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-operator-project
  name: memcached-sample
spec:
  # TODO(user): Add fields here
